cluster_monitor:
  supervisor:
    docker_node_down_threshold_sec: 30
  renderer:
    init_interval_sec: 300
    display_update_interval_sec: 5
  remote_service:
    ssh:
      user: ''
      key_path: ''
      command_rpi_status: "PYTHONPATH=/mnt/data/ePaperHat python3 -m cluster_monitor -mc"
      command_rpi_hdd_status: "PYTHONPATH=/mnt/data/ePaperHat python3 -m cluster_monitor -mc-hdd"